/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeachersIndexRouteImport } from './routes/teachers/index'
import { Route as LessonsIndexRouteImport } from './routes/lessons/index'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as LessonsNewRouteImport } from './routes/lessons/new'
import { Route as LessonsLessonIdRouteImport } from './routes/lessons/$lessonId'
import { Route as LessonsEditLessonIdRouteImport } from './routes/lessons/edit/$lessonId'

const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeachersIndexRoute = TeachersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeachersRoute,
} as any)
const LessonsIndexRoute = LessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => rootRouteImport,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsNewRoute = LessonsNewRouteImport.update({
  id: '/lessons/new',
  path: '/lessons/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsLessonIdRoute = LessonsLessonIdRouteImport.update({
  id: '/lessons/$lessonId',
  path: '/lessons/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsEditLessonIdRoute = LessonsEditLessonIdRouteImport.update({
  id: '/lessons/edit/$lessonId',
  path: '/lessons/edit/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/progress': typeof ProgressRoute
  '/teachers': typeof TeachersRouteWithChildren
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/lessons/new': typeof LessonsNewRoute
  '/s/$slug': typeof SSlugRoute
  '/lessons/': typeof LessonsIndexRoute
  '/teachers/': typeof TeachersIndexRoute
  '/lessons/edit/$lessonId': typeof LessonsEditLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/progress': typeof ProgressRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/lessons/new': typeof LessonsNewRoute
  '/s/$slug': typeof SSlugRoute
  '/lessons': typeof LessonsIndexRoute
  '/teachers': typeof TeachersIndexRoute
  '/lessons/edit/$lessonId': typeof LessonsEditLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/progress': typeof ProgressRoute
  '/teachers': typeof TeachersRouteWithChildren
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/lessons/new': typeof LessonsNewRoute
  '/s/$slug': typeof SSlugRoute
  '/lessons/': typeof LessonsIndexRoute
  '/teachers/': typeof TeachersIndexRoute
  '/lessons/edit/$lessonId': typeof LessonsEditLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/progress'
    | '/teachers'
    | '/lessons/$lessonId'
    | '/lessons/new'
    | '/s/$slug'
    | '/lessons/'
    | '/teachers/'
    | '/lessons/edit/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/progress'
    | '/lessons/$lessonId'
    | '/lessons/new'
    | '/s/$slug'
    | '/lessons'
    | '/teachers'
    | '/lessons/edit/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/progress'
    | '/teachers'
    | '/lessons/$lessonId'
    | '/lessons/new'
    | '/s/$slug'
    | '/lessons/'
    | '/teachers/'
    | '/lessons/edit/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProgressRoute: typeof ProgressRoute
  TeachersRoute: typeof TeachersRouteWithChildren
  LessonsLessonIdRoute: typeof LessonsLessonIdRoute
  LessonsNewRoute: typeof LessonsNewRoute
  SSlugRoute: typeof SSlugRoute
  LessonsIndexRoute: typeof LessonsIndexRoute
  LessonsEditLessonIdRoute: typeof LessonsEditLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teachers/': {
      id: '/teachers/'
      path: '/'
      fullPath: '/teachers/'
      preLoaderRoute: typeof TeachersIndexRouteImport
      parentRoute: typeof TeachersRoute
    }
    '/lessons/': {
      id: '/lessons/'
      path: '/lessons'
      fullPath: '/lessons/'
      preLoaderRoute: typeof LessonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/new': {
      id: '/lessons/new'
      path: '/lessons/new'
      fullPath: '/lessons/new'
      preLoaderRoute: typeof LessonsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$lessonId': {
      id: '/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/lessons/$lessonId'
      preLoaderRoute: typeof LessonsLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/edit/$lessonId': {
      id: '/lessons/edit/$lessonId'
      path: '/lessons/edit/$lessonId'
      fullPath: '/lessons/edit/$lessonId'
      preLoaderRoute: typeof LessonsEditLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TeachersRouteChildren {
  TeachersIndexRoute: typeof TeachersIndexRoute
}

const TeachersRouteChildren: TeachersRouteChildren = {
  TeachersIndexRoute: TeachersIndexRoute,
}

const TeachersRouteWithChildren = TeachersRoute._addFileChildren(
  TeachersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProgressRoute: ProgressRoute,
  TeachersRoute: TeachersRouteWithChildren,
  LessonsLessonIdRoute: LessonsLessonIdRoute,
  LessonsNewRoute: LessonsNewRoute,
  SSlugRoute: SSlugRoute,
  LessonsIndexRoute: LessonsIndexRoute,
  LessonsEditLessonIdRoute: LessonsEditLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
