/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LessonsIndexRouteImport } from './routes/lessons/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SSlugRouteImport } from './routes/s.$slug'
import { Route as LessonsNewRouteImport } from './routes/lessons/new'
import { Route as LessonsLessonIdRouteImport } from './routes/lessons/$lessonId'
import { Route as LessonsEditLessonIdRouteImport } from './routes/lessons/edit/$lessonId'

const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsIndexRoute = LessonsIndexRouteImport.update({
  id: '/lessons/',
  path: '/lessons/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SSlugRoute = SSlugRouteImport.update({
  id: '/s/$slug',
  path: '/s/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsNewRoute = LessonsNewRouteImport.update({
  id: '/lessons/new',
  path: '/lessons/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsLessonIdRoute = LessonsLessonIdRouteImport.update({
  id: '/lessons/$lessonId',
  path: '/lessons/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)
const LessonsEditLessonIdRoute = LessonsEditLessonIdRouteImport.update({
  id: '/lessons/edit/$lessonId',
  path: '/lessons/edit/$lessonId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/progress': typeof ProgressRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/lessons/new': typeof LessonsNewRoute
  '/s/$slug': typeof SSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/lessons/': typeof LessonsIndexRoute
  '/lessons/edit/$lessonId': typeof LessonsEditLessonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/progress': typeof ProgressRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/lessons/new': typeof LessonsNewRoute
  '/s/$slug': typeof SSlugRoute
  '/admin': typeof AdminIndexRoute
  '/lessons': typeof LessonsIndexRoute
  '/lessons/edit/$lessonId': typeof LessonsEditLessonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/progress': typeof ProgressRoute
  '/lessons/$lessonId': typeof LessonsLessonIdRoute
  '/lessons/new': typeof LessonsNewRoute
  '/s/$slug': typeof SSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/lessons/': typeof LessonsIndexRoute
  '/lessons/edit/$lessonId': typeof LessonsEditLessonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/progress'
    | '/lessons/$lessonId'
    | '/lessons/new'
    | '/s/$slug'
    | '/admin/'
    | '/lessons/'
    | '/lessons/edit/$lessonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/progress'
    | '/lessons/$lessonId'
    | '/lessons/new'
    | '/s/$slug'
    | '/admin'
    | '/lessons'
    | '/lessons/edit/$lessonId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/progress'
    | '/lessons/$lessonId'
    | '/lessons/new'
    | '/s/$slug'
    | '/admin/'
    | '/lessons/'
    | '/lessons/edit/$lessonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ProgressRoute: typeof ProgressRoute
  LessonsLessonIdRoute: typeof LessonsLessonIdRoute
  LessonsNewRoute: typeof LessonsNewRoute
  SSlugRoute: typeof SSlugRoute
  LessonsIndexRoute: typeof LessonsIndexRoute
  LessonsEditLessonIdRoute: typeof LessonsEditLessonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/': {
      id: '/lessons/'
      path: '/lessons'
      fullPath: '/lessons/'
      preLoaderRoute: typeof LessonsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/s/$slug': {
      id: '/s/$slug'
      path: '/s/$slug'
      fullPath: '/s/$slug'
      preLoaderRoute: typeof SSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/new': {
      id: '/lessons/new'
      path: '/lessons/new'
      fullPath: '/lessons/new'
      preLoaderRoute: typeof LessonsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/$lessonId': {
      id: '/lessons/$lessonId'
      path: '/lessons/$lessonId'
      fullPath: '/lessons/$lessonId'
      preLoaderRoute: typeof LessonsLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lessons/edit/$lessonId': {
      id: '/lessons/edit/$lessonId'
      path: '/lessons/edit/$lessonId'
      fullPath: '/lessons/edit/$lessonId'
      preLoaderRoute: typeof LessonsEditLessonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ProgressRoute: ProgressRoute,
  LessonsLessonIdRoute: LessonsLessonIdRoute,
  LessonsNewRoute: LessonsNewRoute,
  SSlugRoute: SSlugRoute,
  LessonsIndexRoute: LessonsIndexRoute,
  LessonsEditLessonIdRoute: LessonsEditLessonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
